#!/bin/bash
# Custom bash profile

export NAME="Frank Navarro" export TERM=xterm-256color
export LANG=en_US.UTF-8
export VISUAL=nvim
export EDITOR="$VISUAL"

function minify-json() {
  TEMP_FILE="/tmp/JSON.tmp"
  FILE="$1"
  if [[ ! -z "$FILE" ]]; then
    jq -c . $FILE > $TEMP_FILE && mv $TEMP_FILE $FILE && pbcopy < $FILE
  fi
}

function filesize() {
  check_dir="."
  if [[ ! -z "$1" ]]; then
    check_dir="$1"
  fi

  dir_sizes=$(du -h -d 1 "$check_dir" | sort -nr)
  IFS=, read -r -a units <<< "Y,Z,E,P,T,G,M,K"
  sorted_dirs=""

  for unit in "${units[@]}"; do
    sorted_dirs+=$(echo "$dir_sizes" | awk '$1 ~ /'"$unit"'$/ {print}' )
  done
  echo "$sorted_dirs"
}

